/****************************************************************************
*   Generated by ACUITY 6.21.1
*   Match ovxlib 1.1.30
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_H_
#define _VNN_POST_PROCESS_H_

#define MAX_OBJECT_NUM 2000

typedef struct Rect_s{
    float width;
    float height;
    float x;
    float y;
}Rect;

typedef struct Object_s {
        Rect rect;
        int label;
        float prob;
}Object;

typedef struct Objects_s {
    Object obj[MAX_OBJECT_NUM];
    int num;
}Objects;

#include <vector>
vsi_status vnn_PostProcessYolov5sUint8(vsi_nn_graph_t *graph, std::vector<Object>& objects);

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

uint32_t vnn_GetPostProcessMapCount();

#endif
